---
- name: capture os info
  hosts: all
  tasks: 
    - name: display os name 
      debug: msg="{{ansible_distribution}}"
    - name: display os name
      debug: msg="{{ansible_distribution_version}}"
    - name: display major version info
      debug: msg="{{ansible_distribution_major_version}}"
