---
- name: check folder 1
  hosts: all
  tasks:
    - name: check f1 present or not
      stat:
        path: /tmp/f1
      register: a
    - name: print
      debug:
        var: a
    - name: create f1 file
      file:
        name: /tmp/f1
        state: touch
      when: not a.stat.exists        
