---
- name: Install required s/w's for ci-cd
  hosts: all
  tasks: 
    - name: Install s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
         - {a: openjdk-8-jdk,b: present,c: yes}
         - {a: git,b: present,c: no}
         - {a: maven,b: present,c: no}
         - {a: tomcat9,b: present,c: no}
         - {a: tomcat9-admin,b: present,c: no}
- name: continous download and continous build
  hosts: devserver
  tasks:
    - name: download java code from git
      git:
        repo: https://github.com/intelliqittrainings/maven.git
        dest: dev-git
    - name: cretae artifact from the code
      shell: cd dev-git;mvn package
    - name: fetch artifact
      fetch:
         src: dev-git/webapp/target/webapp.war
         dest: /tmp 
- name: continuous deployment and continuous Testing
  hosts: qaserver
  tasks:
    - name: deploy artifact in to tomcat on the server
      copy: 
        src: /tmp/172.31.87.63/dev-git/webapp/target/webapp.war
        dest: /var/lib/tomcat9/webapps/testapp.war
    - name: Download selenium scripts
      git:
        repo: https://github.com/intelliqittrainings/FunctionalTesting.git
        dest: test-git
    - name: Execute the selenium scripts
      shell: java -jar test-git/testing.jar
- name: continuous delivery
  hosts: prodserver
  tasks:
    - name: deploy artifact into tomcat on the prodservers
      copy:
        src: /tmp/172.31.87.63/dev-git/webapp/target/webapp.war
        dest: /var/lib/tomcat9/webapps/prodapp.war

  
