---
- name: Implementing a host scope varaibles
  hosts: 172.31.87.17
  tasks:
    - name: create user
      user: 
         name: "{{a}}"
         password: "{{b}}"
         uid: "{{c}}"
         home: "{{d}}"
         shell: "{{e}}"
...           
