---
- name: configuring tomcat
  hosts: all
  tasks: 
     - name: install tomcat9
       apt: 
         name: "{{item.a}}"
         state: "{{item.b}}"
         update_cache: "{{item.c}}"
       with_items:
         - {a: tomcat9,b: present,c: yes}
         - {a: tomcat9-admin,b: present,c: no}  
     - name: copy the tomcat-users.xml file
       copy:
         src: tomcat-users.xml
         dest: /etc/tomcat9
     - name: change port of tomcat9 from 8080 to 9090
       replace:
         regexp: 8080
         replace: 9090
         path: /etc/tomcat9/server.xml
     - name: restart tomcat
       service: 
         name: tomcat9
         state: restarted
     - name: pause for 1 mins
       pause:
         minutes: 1
     - name: check tomcat response on all servers
       uri: 
         url: "{{item}}"
         status_code: 200
       with_items:
          - http://172.31.87.17
          - http://172.31.88.129
...  
           
